const sb=window.supabase.createClient('https://ygslzwiznvcfujonvblq.supabase.co','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ5Z3Nsendpem52Y2Z1am9udmJscSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzgwMDQzODY5LCJleHAiOjIwOTU2MTk4NjB9.J9P1NyK5tiSzPZgDeLpwfS2eRaFrP5Gb4fgpmA258vA')
const sourceLabels={gacha:'转盘',season:'赛季',luxury:'臻藏',flip:'翻牌',gift:'直售/赠礼',direct:'直售',free:'免费获取',activity:'活动',shop:'商店',none:'未注明',new:'首次上线',restock:'历史返场',balance:'平衡调整',default:'其它'}
const OWNED_KEY='hogwarts_catalog_owned_v1'
const params=new URLSearchParams(location.search)
let catalog={categories:[],items:[]},active=params.get('type')||'all',query=params.get('q')||'',year=params.get('year')||'all',source=params.get('source')||'all',owned=readOwned(),detailId=params.get('item')||''
const grid=document.getElementById('grid'),input=document.getElementById('searchInput'),mask=document.getElementById('detailMask'),yearSelect=document.getElementById('yearFilter'),sourceSelect=document.getElementById('sourceFilter')

input.value=query
fetch('catalog-data.json').then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(data=>{catalog=data;buildFilters();render();if(detailId)openDetail(detailId,false)}).catch(()=>{grid.innerHTML='<div class="empty"><b>资料暂时没有同步</b><br>请稍后刷新重试</div>';document.getElementById('resultCount').textContent='加载失败'})
function buildFilters(){
  if(!catalog.categories.some(x=>x.key===active))active='all'
  document.getElementById('filters').innerHTML=[{key:'all',label:'全部',icon:'✦',count:catalog.items.length},...catalog.categories].map(x=>`<button class="chip ${x.key===active?'active':''}" data-key="${x.key}">${x.icon} ${x.label} · ${x.count}</button>`).join('')
  yearSelect.innerHTML='<option value="all">全部年份</option>'+catalog.years.map(x=>`<option value="${esc(x)}">${esc(x)}年</option>`).join('')
  sourceSelect.innerHTML='<option value="all">全部来源</option>'+catalog.sources.map(x=>`<option value="${esc(x.key)}">${esc(x.label)}</option>`).join('')
  yearSelect.value=catalog.years.includes(year)?year:'all';year=yearSelect.value
  sourceSelect.value=catalog.sources.some(x=>x.key===source)?source:'all';source=sourceSelect.value
}
function searchText(x){return [x.name,x.alternateName,...(x.aliases||[]),x.year,x.date,x.categoryLabel,x.source,x.sourceLabel,x.categoryDetail,x.season,x.seasonName,...(x.details||[])].join(' ').toLowerCase()}
function filtered(){const q=query.toLowerCase();return catalog.items.filter(x=>(active==='all'||x.category===active)&&(year==='all'||String(x.year).includes(year))&&(source==='all'||x.source===source)&&(!q||searchText(x).includes(q)))}
function render(){const list=filtered(),cat=catalog.categories.find(x=>x.key===active);document.getElementById('resultTitle').textContent=query?'搜索结果':cat?cat.label:'全部资料';document.getElementById('resultCount').textContent=`共 ${list.length} 条`;grid.innerHTML=list.length?list.map(card).join(''):'<div class="empty"><b>没有找到相关资料</b><br>换个关键词或筛选条件试试</div>';syncUrl()}
function card(x){const has=x.collectible&&owned.has(x.id),source=x.sourceLabel||sourceLabels[x.source]||x.source||'来源待补充';return `<button class="card ${has?'owned':''}" data-id="${esc(x.id)}"><span class="thumb">${x.image?`<img src="${esc(x.image)}" alt="" loading="lazy" onerror="this.parentNode.textContent='${x.icon}'">`:x.icon}</span><span class="card-body"><span class="card-head"><span class="type">${x.categoryLabel}</span><span class="date">${esc([x.year,x.date].filter(Boolean).join(' '))}</span></span><span class="name">${esc(x.name)}</span>${x.alternateName?`<span class="alt">别名：${esc(x.alternateName)}</span>`:''}<span class="meta">${esc(source)}${x.rarity?' · '+esc(x.rarity):''}</span></span>${has?'<span class="owned-mark">✓ 已拥有</span>':''}</button>`}
function openDetail(id,push=true){const x=catalog.items.find(i=>i.id===id);if(!x)return;detailId=id;document.getElementById('detailTitle').textContent=x.name;const event=x.flipEvent?`<div class="event"><b>${esc(x.flipEvent.eventName||'活动信息')}</b><br>${x.flipEvent.item?'道具：'+esc(x.flipEvent.item)+'<br>':''}${x.flipEvent.cost?'参考消耗：'+esc(x.flipEvent.cost):''}</div>`:'';const details=(x.details||[]).length?`<div class="detail-notes">${x.details.map(line=>`<p>${esc(line)}</p>`).join('')}</div>`:'';const has=owned.has(id);document.getElementById('detailContent').innerHTML=`<div class="detail-image">${x.image?`<img src="${esc(x.image)}" alt="${esc(x.name)}" onerror="this.parentNode.textContent='${x.icon}'">`:x.icon}</div><div class="row"><span>分类</span><span>${x.categoryLabel}</span></div><div class="row"><span>名称</span><span>${esc(x.name)}</span></div>${x.alternateName?`<div class="row"><span>别名</span><span>${esc(x.alternateName)}</span></div>`:''}<div class="row"><span>时间</span><span>${esc([x.year,x.date].filter(Boolean).join(' '))||'待补充'}</span></div><div class="row"><span>来源</span><span>${esc(x.sourceLabel||sourceLabels[x.source]||x.source||'待补充')}</span></div>${x.categoryDetail?`<div class="row"><span>所属</span><span>${esc(x.categoryDetail)}</span></div>`:''}${details}${event}<button class="copy-btn" id="copyLinkBtn">复制资料链接</button>${x.collectible?`<button class="own-btn ${has?'is-owned':''}" id="ownBtn">${has?'✓ 已拥有 · 点击取消':'＋ 标记为已拥有'}</button>`:''}`;document.getElementById('copyLinkBtn').onclick=copyDetailLink;if(x.collectible)document.getElementById('ownBtn').onclick=toggleOwned;mask.classList.add('open');document.body.style.overflow='hidden';if(push)syncUrl()}
document.getElementById('filters').onclick=e=>{const b=e.target.closest('.chip');if(!b)return;active=b.dataset.key;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===b));render()}
grid.onclick=e=>{const b=e.target.closest('.card');if(b)openDetail(b.dataset.id)}
input.oninput=()=>{query=input.value.trim();render()};yearSelect.onchange=()=>{year=yearSelect.value;render()};sourceSelect.onchange=()=>{source=sourceSelect.value;render()}
document.getElementById('clearBtn').onclick=()=>{input.value='';query='';year='all';source='all';yearSelect.value='all';sourceSelect.value='all';render();input.focus()}
document.querySelector('.close').onclick=closeDetail;mask.onclick=e=>{if(e.target===mask)closeDetail()};document.onkeydown=e=>{if(e.key==='Escape')closeDetail()}
function closeDetail(){mask.classList.remove('open');document.body.style.overflow='';detailId='';syncUrl()}
function syncUrl(){const next=new URLSearchParams();if(query)next.set('q',query);if(active!=='all')next.set('type',active);if(year!=='all')next.set('year',year);if(source!=='all')next.set('source',source);if(detailId)next.set('item',detailId);history.replaceState(null,'',location.pathname+(next.size?'?'+next:'')+location.hash)}
async function copyDetailLink(){const url=new URL(location.href);url.search='';url.searchParams.set('item',detailId);try{await navigator.clipboard.writeText(url.href);document.getElementById('copyLinkBtn').textContent='链接已复制'}catch{prompt('复制资料链接',url.href)}}
function readOwned(){try{return new Set(JSON.parse(localStorage.getItem(OWNED_KEY)||'[]'))}catch{return new Set()}}
function toggleOwned(){if(!detailId)return;owned.has(detailId)?owned.delete(detailId):owned.add(detailId);localStorage.setItem(OWNED_KEY,JSON.stringify([...owned]));render();openDetail(detailId,false)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
document.getElementById('miniLink').onclick=()=>document.querySelector('#miniProgramEntry .mp-fab')?.click()
HW.mountMiniProgramEntry(sb)
