-- 魔法创作广场（外部网站专用）。先在 Authentication 中开启匿名登录。
create extension if not exists pgcrypto;

create table if not exists public.creation_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null check(char_length(nickname) between 2 and 20),
  status text not null default 'active' check(status in ('active','suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.is_creation_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.creation_admins where user_id=auth.uid()) $$;

create or replace function public.has_email_identity()
returns boolean language sql stable security definer set search_path=auth,public
as $$ select coalesce(auth.jwt()->>'email','') <> '' $$;

create table if not exists public.creation_works (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null check(category in ('album','outfit','art','meme','guide')),
  title text not null check(char_length(title) between 1 and 50),
  body text not null default '' check(char_length(body)<=1000),
  author_name text not null default '' check(char_length(author_name)<=20),
  image_paths text[] not null check(cardinality(image_paths) between 1 and 6),
  status text not null default 'pending' check(status in ('pending','approved','rejected')),
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.creation_favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  work_id uuid not null references public.creation_works(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id,work_id)
);

create table if not exists public.creation_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  work_id uuid not null references public.creation_works(id) on delete cascade,
  reason text not null check(char_length(reason) between 1 and 200),
  status text not null default 'pending' check(status in ('pending','resolved','dismissed')),
  created_at timestamptz not null default now(),
  unique(reporter_id,work_id)
);

create table if not exists public.deck_submissions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check(char_length(title) between 1 and 50),
  mode text not null check(mode in ('单排','双排','PVE')),
  echo_name text not null check(char_length(echo_name) between 1 and 30),
  cards jsonb not null check(jsonb_typeof(cards)='array' and jsonb_array_length(cards)=8),
  partners jsonb not null check(jsonb_typeof(partners)='array' and jsonb_array_length(partners)=3),
  description text not null default '' check(char_length(description)<=1500),
  author_name text not null default '' check(char_length(author_name)<=20),
  game_version text not null default '' check(char_length(game_version)<=30),
  status text not null default 'pending' check(status in ('pending','approved','rejected','archived')),
  featured boolean not null default false,
  selected_for_miniprogram boolean not null default false,
  review_note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  exported_at timestamptz
);

alter table public.creation_admins enable row level security;
alter table public.creation_works enable row level security;
alter table public.creation_favorites enable row level security;
alter table public.creation_reports enable row level security;
alter table public.profiles enable row level security;
alter table public.deck_submissions enable row level security;

create policy "read approved works" on public.creation_works for select using(status='approved' or user_id=auth.uid() or public.is_creation_admin());
create policy "submit own works" on public.creation_works for insert to authenticated with check(public.has_email_identity() and user_id=auth.uid() and status='pending' and featured=false);
create policy "delete own pending works" on public.creation_works for delete to authenticated using((user_id=auth.uid() and status='pending') or public.is_creation_admin());
create policy "admin updates works" on public.creation_works for update to authenticated using(public.is_creation_admin()) with check(public.is_creation_admin());
create policy "read own favorites" on public.creation_favorites for select to authenticated using(user_id=auth.uid());
create policy "create own favorites" on public.creation_favorites for insert to authenticated with check(public.has_email_identity() and user_id=auth.uid());
create policy "delete own favorites" on public.creation_favorites for delete to authenticated using(user_id=auth.uid());
create policy "create reports" on public.creation_reports for insert to authenticated with check(public.has_email_identity() and reporter_id=auth.uid());
create policy "admin reads reports" on public.creation_reports for select to authenticated using(public.is_creation_admin());
create policy "admin updates reports" on public.creation_reports for update to authenticated using(public.is_creation_admin());
create policy "public reads profiles" on public.profiles for select using(true);
create policy "users create profile" on public.profiles for insert to authenticated with check(public.has_email_identity() and user_id=auth.uid());
create policy "users update profile" on public.profiles for update to authenticated using(public.has_email_identity() and user_id=auth.uid()) with check(public.has_email_identity() and user_id=auth.uid());
create policy "read deck submissions" on public.deck_submissions for select using(status='approved' or user_id=auth.uid() or public.is_creation_admin());
create policy "submit own decks" on public.deck_submissions for insert to authenticated with check(public.has_email_identity() and user_id=auth.uid() and status='pending' and featured=false and selected_for_miniprogram=false);
create policy "delete own pending decks" on public.deck_submissions for delete to authenticated using((user_id=auth.uid() and status='pending') or public.is_creation_admin());
create policy "admin updates decks" on public.deck_submissions for update to authenticated using(public.is_creation_admin()) with check(public.is_creation_admin());

grant execute on function public.is_creation_admin() to anon,authenticated;
grant execute on function public.has_email_identity() to anon,authenticated;
grant select,insert,update,delete on public.creation_works to authenticated;
grant select,insert,delete on public.creation_favorites to authenticated;
grant select,insert,update on public.creation_reports to authenticated;
grant select,insert,update on public.profiles to anon,authenticated;
grant select,insert,update,delete on public.deck_submissions to authenticated;
grant select on public.deck_submissions to anon;
grant usage,select on sequence public.creation_reports_id_seq to authenticated;
create index if not exists creation_works_public_idx on public.creation_works(status,featured desc,created_at desc);
create index if not exists creation_works_category_idx on public.creation_works(category,status,created_at desc);
create index if not exists creation_reports_queue_idx on public.creation_reports(status,created_at desc);
create index if not exists deck_submissions_public_idx on public.deck_submissions(status,featured desc,created_at desc);
create index if not exists deck_submissions_export_idx on public.deck_submissions(selected_for_miniprogram,status,updated_at desc);

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('creation-images','creation-images',true,8388608,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict(id) do update set public=true,file_size_limit=8388608,allowed_mime_types=excluded.allowed_mime_types;
create policy "public reads creation images" on storage.objects for select using(bucket_id='creation-images');
create policy "users upload own creation images" on storage.objects for insert to authenticated with check(bucket_id='creation-images' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "users delete own creation images" on storage.objects for delete to authenticated using(bucket_id='creation-images' and ((storage.foldername(name))[1]=auth.uid()::text or public.is_creation_admin()));

-- 执行 migration 后，把管理员 UUID 加入白名单：
-- insert into public.creation_admins(user_id) values ('你的 Supabase Auth 用户 UUID');
