const SUPABASE_URL='https://ygslzwiznvcfujonvblq.supabase.co',SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlnc2x6d2l6bnZjZnVqb252YmxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAwNDM4NjksImV4cCI6MjA5NTYxOTg2OX0.J9P1NyK5tiSzPZgDeLpwfS2eRaFrP5Gb4fgpmA258vA'
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY),BUCKET='creation-images'
const categories=[['all','全部'],['album','玩家相册'],['outfit','穿搭'],['art','绘画手作'],['meme','梗图'],['guide','攻略']],labels=Object.fromEntries(categories)
let user=null,isAdmin=false,mode='public',category='all',works=[],favorites=new Set(),timer
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('show'),2200)}
function requireEmail(){if(user?.email)return true;location.href='account.html';return false}
function setMode(next){if(next==='mine'&&!requireEmail())return;mode=next;['public','mine','review'].forEach(x=>$(x+'Tab')?.classList.toggle('active',x===mode));load()}
function imageUrl(path){return sb.storage.from(BUCKET).getPublicUrl(path).data.publicUrl}
async function init(){const identity=await HW.ensureAuth(sb);if(identity.isLocalIdentity){$('publishBtn').disabled=true;toast('请先在 Supabase 开启匿名登录');return}user=identity;isAdmin=Boolean((await sb.rpc('is_creation_admin')).data);$('reviewTab').hidden=!isAdmin;$('filters').innerHTML=categories.map(([key,label])=>`<button data-key="${key}" class="${key==='all'?'active':''}">${label}</button>`).join('');$('filters').onclick=e=>{const b=e.target.closest('[data-key]');if(!b)return;category=b.dataset.key;[...$('filters').children].forEach(x=>x.classList.toggle('active',x===b));load()};$('publicTab').onclick=()=>setMode('public');$('mineTab').onclick=()=>setMode('mine');$('reviewTab').onclick=()=>setMode('review');$('publishBtn').onclick=()=>{if(requireEmail())$('modal').classList.add('open')};$('closeBtn').onclick=()=>$('modal').classList.remove('open');$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.remove('open')};$('images').onchange=preview;$('form').onsubmit=submit;await loadFavorites();await load()}
async function loadFavorites(){const{data}=await sb.from('creation_favorites').select('work_id').eq('user_id',user.id);favorites=new Set((data||[]).map(x=>x.work_id))}
async function load(){let q=sb.from('creation_works').select('*').order('featured',{ascending:false}).order('created_at',{ascending:false}).limit(100);if(mode==='public')q=q.eq('status','approved');if(mode==='mine')q=q.eq('user_id',user.id);if(mode==='review')q=q.eq('status','pending');if(category!=='all')q=q.eq('category',category);const{data,error}=await q;if(error){$('grid').innerHTML=`<div class="empty">加载失败：${esc(error.message)}</div>`;return}works=data||[];render()}
function render(){$('count').textContent=`共 ${works.length} 件`;$('grid').innerHTML=works.length?works.map(card).join(''):'<div class="empty">这里暂时没有作品</div>'}
function card(w){const image=(w.image_paths||[])[0],own=w.user_id===user.id,admin=isAdmin,status=mode==='public'?'':` · ${w.status==='pending'?'待审核':w.status==='approved'?'已通过':'未通过'}`;return `<article class="card">${image?`<img src="${esc(imageUrl(image))}" alt="" loading="lazy">`:''}<div class="card-body"><div class="meta"><span>${esc(labels[w.category]||'其他')}${status}</span>${w.featured?'<span class="featured">✦ 精选</span>':''}</div><h2>${esc(w.title)}</h2>${w.body?`<p>${esc(w.body)}</p>`:''}${w.author_name?`<div class="meta">作者：${esc(w.author_name)}</div>`:''}<div class="actions">${mode==='public'?`<button onclick="toggleFavorite('${w.id}')">${favorites.has(w.id)?'★ 已收藏':'☆ 收藏'}</button><button onclick="reportWork('${w.id}')">举报</button>`:''}${own&&w.status==='pending'?`<button class="danger" onclick="deleteWork('${w.id}')">撤回投稿</button>`:''}${admin&&mode==='review'?`<button onclick="moderate('${w.id}','approved')">通过</button><button class="danger" onclick="moderate('${w.id}','rejected')">拒绝</button>`:''}${admin&&w.status==='approved'?`<button onclick="featureWork('${w.id}',${!w.featured})">${w.featured?'取消精选':'设为精选'}</button>`:''}</div></div></article>`}
function preview(){const files=[...$('images').files].slice(0,6);$('preview').innerHTML=files.map(f=>`<img src="${URL.createObjectURL(f)}" alt="">`).join('')}
async function submit(e){e.preventDefault();if(!requireEmail())return;const files=[...$('images').files];if(!files.length||files.length>6)return toast('请选择1～6张图片');if(files.some(f=>f.size>8*1024*1024))return toast('单张图片不能超过8MB');$('submitBtn').disabled=true;$('submitBtn').textContent='上传中…';const paths=[];try{for(const file of files){const ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`${user.id}/${crypto.randomUUID()}.${ext}`,{error}=await sb.storage.from(BUCKET).upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;paths.push(path)}const row={user_id:user.id,category:$('category').value,title:$('title').value.trim(),author_name:$('author').value.trim(),body:$('body').value.trim(),image_paths:paths,status:'pending',featured:false},{error}=await sb.from('creation_works').insert(row);if(error)throw error;$('form').reset();$('preview').innerHTML='';$('modal').classList.remove('open');toast('投稿成功，审核通过后公开');setMode('mine')}catch(err){if(paths.length)await sb.storage.from(BUCKET).remove(paths);toast('投稿失败：'+err.message)}finally{$('submitBtn').disabled=false;$('submitBtn').textContent='提交审核'}}
window.toggleFavorite=async id=>{if(!requireEmail())return;if(favorites.has(id)){const{error}=await sb.from('creation_favorites').delete().eq('user_id',user.id).eq('work_id',id);if(error)return toast(error.message);favorites.delete(id)}else{const{error}=await sb.from('creation_favorites').insert({user_id:user.id,work_id:id});if(error)return toast(error.message);favorites.add(id)}render()}
window.reportWork=async id=>{if(!requireEmail())return;const reason=prompt('举报原因（请勿填写个人隐私）');if(!reason?.trim())return;const{error}=await sb.from('creation_reports').insert({reporter_id:user.id,work_id:id,reason:reason.trim().slice(0,200)});toast(error?(error.code==='23505'?'你已经举报过该作品':'举报失败：'+error.message):'举报已提交')}
window.moderate=async(id,status)=>{const{error}=await sb.from('creation_works').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message);load()}
window.featureWork=async(id,featured)=>{const{error}=await sb.from('creation_works').update({featured,updated_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message);load()}
window.deleteWork=async id=>{if(!confirm('撤回后将删除作品和图片，确定继续？'))return;const work=works.find(x=>x.id===id),{error}=await sb.from('creation_works').delete().eq('id',id).eq('user_id',user.id);if(error)return toast(error.message);if(work?.image_paths?.length)await sb.storage.from(BUCKET).remove(work.image_paths);load()}
init();HW.mountMiniProgramEntry(sb)
