const STORAGE_KEY='hogwarts_resource_plans_v1'
let data={resources:[],activities:[]},state={plans:[],activeId:''}
const $=id=>document.getElementById(id)
const esc=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))
const fmt=value=>Number(value||0).toLocaleString('zh-CN',{maximumFractionDigits:2})
const iso=date=>date.toISOString().slice(0,10)
const addDays=(date,days)=>{const next=new Date(date);next.setDate(next.getDate()+days);return next}

fetch('planner-data.json').then(r=>r.json()).then(value=>{data=value;loadState();renderAll()}).catch(error=>{$('resultSummary').innerHTML='<div class="empty-row">规划规则加载失败，请刷新重试</div>';console.error(error)})

function defaultPlan(name,index){const now=new Date(),end=addDays(now,56);return {id:'plan-'+index,name,startDate:iso(now),endDate:iso(end),balances:[{resource:'金币',amount:0},{resource:'宝石',amount:0},{resource:'金钥匙',amount:0},{resource:'红钥匙',amount:0}],goals:[{resource:'宝石',amount:1000,targetDate:iso(end)}],expenses:[],activityIds:[]}}
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(saved&&Array.isArray(saved.plans)&&saved.plans.length)state=saved}catch{}if(!state.plans.length)state={plans:[defaultPlan('休闲方案',1),defaultPlan('全勤方案',2),defaultPlan('月卡方案',3)],activeId:'plan-1'};if(!state.plans.some(p=>p.id===state.activeId))state.activeId=state.plans[0].id}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('saveState').textContent='已自动保存 · '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}
function plan(){return state.plans.find(item=>item.id===state.activeId)}
function resourceOptions(selected){return data.resources.map(item=>`<option value="${esc(item.name)}" ${item.name===selected?'selected':''}>${esc(item.icon||'•')} ${esc(item.name)}</option>`).join('')}
function rewardText(rewards){return Object.entries(rewards||{}).map(([name,value])=>`${name} × ${fmt(value)}`).join('、')}

function renderAll(){renderTabs();renderEditor();renderActivities();renderResults();renderTimeline();renderCompare()}
function renderTabs(){$('planTabs').innerHTML=state.plans.map(item=>`<button class="plan-tab ${item.id===state.activeId?'active':''}" data-plan="${item.id}"><b>${esc(item.name)}</b><span>${esc(item.startDate)} → ${esc(item.endDate)}</span></button>`).join('')}
function renderEditor(){const current=plan();$('planName').value=current.name;$('startDate').value=current.startDate;$('endDate').value=current.endDate
  $('balanceRows').innerHTML=current.balances.length?current.balances.map((row,index)=>`<div class="data-row"><select data-list="balances" data-index="${index}" data-field="resource">${resourceOptions(row.resource)}</select><input type="number" min="0" step="any" value="${row.amount}" data-list="balances" data-index="${index}" data-field="amount" aria-label="当前数量"><button class="remove" data-remove="balance" data-index="${index}">×</button></div>`).join(''):'<div class="empty-row">尚未添加当前资源</div>'
  $('goalRows').innerHTML=current.goals.length?current.goals.map((row,index)=>`<div class="data-row goal"><select data-list="goals" data-index="${index}" data-field="resource">${resourceOptions(row.resource)}</select><input type="number" min="0" step="any" value="${row.amount}" data-list="goals" data-index="${index}" data-field="amount" aria-label="目标数量"><input type="date" value="${row.targetDate||current.endDate}" data-list="goals" data-index="${index}" data-field="targetDate"><button class="remove" data-remove="goal" data-index="${index}">×</button></div>`).join(''):'<div class="empty-row">添加目标后可计算缺口</div>'
  $('expenseRows').innerHTML=current.expenses.length?current.expenses.map((row,index)=>`<div class="data-row expense"><input value="${esc(row.name)}" placeholder="支出名称" data-list="expenses" data-index="${index}" data-field="name"><input type="date" value="${row.date}" data-list="expenses" data-index="${index}" data-field="date"><select data-list="expenses" data-index="${index}" data-field="resource">${resourceOptions(row.resource)}</select><input type="number" min="0" step="any" value="${row.amount}" data-list="expenses" data-index="${index}" data-field="amount" aria-label="支出数量"><button class="remove" data-remove="expense" data-index="${index}">×</button></div>`).join(''):'<div class="empty-row">没有计划支出</div>'
}
function renderActivities(){const current=plan(),selected=new Set(current.activityIds),groups={};data.activities.forEach(item=>(groups[item.group]??=[]).push(item));$('activitySummary').textContent=`已选择 ${selected.size} 项`;$('activityGroups').innerHTML=Object.entries(groups).map(([name,items])=>`<details class="activity-group" ${items.some(x=>selected.has(x.id))?'open':''}><summary>${esc(name)} · ${items.filter(x=>selected.has(x.id)).length}/${items.length}</summary><div class="activity-list">${items.map(item=>`<label class="activity"><input type="checkbox" data-activity="${item.id}" ${selected.has(item.id)?'checked':''}><span>${esc(item.name)} ${item.paid?'<b class="paid">付费</b>':''}</span><span class="reward">${esc(rewardText(item.rewards))}<br>${item.frequency}</span></label>`).join('')}</div></details>`).join('')}
function normalizedPlan(current){return {...current,balances:Object.fromEntries(current.balances.map(x=>[x.resource,Number(x.amount)||0])),expenses:current.expenses.map(x=>({date:x.date,name:x.name,resources:{[x.resource]:Number(x.amount)||0}})),goals:current.goals.map(x=>({...x,amount:Number(x.amount)||0}))}}
function safeResult(current){try{return PlannerCore.calculate(normalizedPlan(current),data.activities)}catch(error){return {error:error.message,days:0,final:{},income:{},expenses:{},goals:[],details:[]}}}
function safeTimeline(current){try{return PlannerCore.timeline(normalizedPlan(current),data.activities)}catch(error){return {error:error.message,rows:[],goals:[]}}}
function renderResults(){const result=safeResult(plan());$('resultDays').textContent=result.error?'日期有误':`${result.days} 天`;if(result.error){$('resultSummary').innerHTML=`<div class="empty-row">${esc(result.error)}</div>`;$('goalSummary').innerHTML='';return}const names=[...new Set([...Object.keys(result.final),...Object.keys(result.income)])];$('resultSummary').innerHTML=names.length?names.sort((a,b)=>(result.final[b]||0)-(result.final[a]||0)).map(name=>`<div class="resource-result"><span>${esc(name)}</span><b class="${result.final[name]<0?'negative':''}">${fmt(result.final[name])}</b><small>收益 +${fmt(result.income[name]||0)} · 支出 -${fmt(result.expenses[name]||0)}</small></div>`).join(''):'<div class="empty-row">添加库存或选择活动后查看结果</div>';$('goalSummary').innerHTML=result.goals.map(goal=>`<div class="goal-card ${goal.achieved?'ok':''}"><strong>${goal.achieved?'✓ 可以达成':'还差 '+fmt(goal.gap)} · ${esc(goal.resource)}</strong>目标 ${fmt(goal.amount)}，预计期末 ${fmt(goal.current)}</div>`).join('')}
function renderCompare(){const results=state.plans.map(item=>({item,result:safeResult(item)})),resources=[...new Set(results.flatMap(x=>Object.keys(x.result.final||{})))];$('compareHead').innerHTML='<tr><th>项目</th>'+results.map(x=>`<th>${esc(x.item.name)}</th>`).join('')+'</tr>';$('compareBody').innerHTML=[`<tr><td>规划天数</td>${results.map(x=>`<td>${x.result.days||'—'}</td>`).join('')}</tr>`,...resources.map(name=>`<tr><td>${esc(name)}期末</td>${results.map(x=>`<td class="${(x.result.final?.[name]||0)<0?'negative':''}">${fmt(x.result.final?.[name]||0)}</td>`).join('')}</tr>`),`<tr><td>已选活动</td>${results.map(x=>`<td>${x.result.details?.length||0}</td>`).join('')}</tr>`,`<tr><td>目标达成</td>${results.map(x=>`<td>${(x.result.goals||[]).filter(g=>g.achieved).length}/${(x.result.goals||[]).length}</td>`).join('')}</tr>`].join('')}
function renderTimeline(){
  const current=plan(),timeline=safeTimeline(current),rows=timeline.rows||[]
  if(timeline.error){$('trendChart').innerHTML=`<div class="empty-row">${esc(timeline.error)}</div>`;$('calendarList').innerHTML='';$('warningSummary').innerHTML='';return}
  const result=safeResult(current),names=Object.keys(result.final||{}).sort((a,b)=>Math.abs(result.final[b]||0)-Math.abs(result.final[a]||0)).slice(0,4)
  $('trendChart').innerHTML=names.length?names.map(name=>{
    const values=[Number(normalizedPlan(current).balances[name]||0),...rows.map(row=>Number(row.balances[name]||0))],min=Math.min(...values),max=Math.max(...values),range=max-min||1
    const points=values.map((value,index)=>`${values.length===1?0:index*100/(values.length-1)},${38-(value-min)*36/range}`).join(' ')
    return `<div class="trend-row ${min<0?'negative':''}"><b>${esc(name)}</b><svg class="spark" viewBox="0 0 100 40" preserveAspectRatio="none" aria-label="${esc(name)}资源趋势"><polyline points="${points}"></polyline></svg><strong>${fmt(values.at(-1))}</strong></div>`
  }).join(''):'<div class="empty-row">添加库存或收益活动后显示趋势</div>'
  const events=rows.filter(row=>Object.keys(row.changes).length).slice(0,12)
  $('calendarList').innerHTML=events.length?events.map(row=>`<article class="calendar-day"><time>${row.date}</time>${Object.entries(row.changes).slice(0,3).map(([name,value])=>`<b>${esc(name)} ${value>=0?'+':''}${fmt(value)}</b>`).join('')}<small>${Object.keys(row.changes).length>3?'另有 '+(Object.keys(row.changes).length-3)+' 项变化':''}</small></article>`).join(''):'<div class="empty-row">当前日期范围内没有资源变化</div>'
  const firstNegative=rows.find(row=>Object.values(row.balances).some(value=>value<0)),negativeNames=firstNegative?Object.entries(firstNegative.balances).filter(([,value])=>value<0).map(([name])=>name):[]
  $('warningSummary').innerHTML=firstNegative?`<div class="warning-card">⚠ ${firstNegative.date} 起，${negativeNames.map(esc).join('、')}预计出现负余额</div>`:''
  const estimates=new Map(timeline.goals.map(goal=>[goal.resource+'|'+goal.amount,goal]))
  $('goalSummary').querySelectorAll('.goal-card').forEach((card,index)=>{const goal=result.goals[index],estimate=estimates.get(goal.resource+'|'+goal.amount);if(estimate?.estimatedDate)card.insertAdjacentHTML('beforeend',`<small>预计 ${estimate.estimatedDate} 达成</small>`);else if(!goal.achieved)card.insertAdjacentHTML('beforeend','<small>本方案周期内无法达成</small>')})
}
function changed(){saveState();renderTabs();renderResults();renderTimeline();renderCompare()}

$('planTabs').onclick=e=>{const button=e.target.closest('[data-plan]');if(!button)return;state.activeId=button.dataset.plan;renderAll()}
document.addEventListener('input',e=>{const current=plan();if(e.target.id==='planName'){current.name=e.target.value;changed();return}if(e.target.id==='startDate'||e.target.id==='endDate'){current[e.target.id]=e.target.value;changed();return}const {list,index,field}=e.target.dataset;if(!list)return;current[list][Number(index)][field]=field==='amount'?Number(e.target.value):e.target.value;changed()})
document.addEventListener('change',e=>{if(e.target.dataset.activity){const ids=new Set(plan().activityIds);e.target.checked?ids.add(e.target.dataset.activity):ids.delete(e.target.dataset.activity);plan().activityIds=[...ids];changed();$('activitySummary').textContent=`已选择 ${ids.size} 项`;return}const {list,index,field}=e.target.dataset;if(list){plan()[list][Number(index)][field]=field==='amount'?Number(e.target.value):e.target.value;changed()}})
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]'),remove=e.target.closest('[data-remove]'),preset=e.target.closest('[data-preset]');if(add){if(add.dataset.add==='balance')plan().balances.push({resource:'金币',amount:0});if(add.dataset.add==='goal')plan().goals.push({resource:'宝石',amount:0,targetDate:plan().endDate});if(add.dataset.add==='expense')plan().expenses.push({name:'',date:plan().endDate,resource:'宝石',amount:0});saveState();renderEditor();renderResults();renderTimeline();renderCompare()}if(remove){const map={balance:'balances',goal:'goals',expense:'expenses'};plan()[map[remove.dataset.remove]].splice(Number(remove.dataset.index),1);saveState();renderEditor();renderResults();renderTimeline();renderCompare()}if(preset)applyPreset(preset.dataset.preset)})
function applyPreset(kind){let ids=[];if(kind==='leisure')ids=data.activities.filter(x=>!x.paid&&!x.limited&&['每日','每周'].includes(x.frequency)).map(x=>x.id);if(kind==='full'||kind==='monthly')ids=data.activities.filter(x=>!x.paid).map(x=>x.id);if(kind==='monthly')ids.push(...data.activities.filter(x=>x.id==='d-mcard').map(x=>x.id));plan().activityIds=[...new Set(ids)];saveState();renderActivities();renderResults();renderTimeline();renderCompare()}
$('copyPlanBtn').onclick=()=>{if(state.plans.length>=6){alert('最多保留 6 套比较方案');return}const source=plan(),copy=JSON.parse(JSON.stringify(source));copy.id='plan-'+Date.now();copy.name=(source.name||'未命名方案')+' 副本';state.plans.push(copy);state.activeId=copy.id;saveState();renderAll()}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('exportBtn').onclick=()=>download(`resource-plans-${iso(new Date())}.json`,JSON.stringify({schemaVersion:1,exportedAt:new Date().toISOString(),...state},null,2),'application/json')
$('csvBtn').onclick=()=>{const rows=[['资源',...state.plans.map(x=>x.name)]];const results=state.plans.map(safeResult),resources=[...new Set(results.flatMap(x=>Object.keys(x.final||{})))];resources.forEach(name=>rows.push([name,...results.map(x=>x.final[name]||0)]));rows.push(['已选活动',...results.map(x=>x.details.length)]);download(`resource-compare-${iso(new Date())}.csv`,'\uFEFF'+rows.map(row=>row.map(x=>`"${String(x).replace(/"/g,'""')}"`).join(',')).join('\n'),'text/csv;charset=utf-8')}
$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{const value=JSON.parse(await file.text());if(!Array.isArray(value.plans)||!value.plans.length)throw Error('文件中没有规划方案');state={plans:value.plans.slice(0,3),activeId:value.activeId||value.plans[0].id};saveState();renderAll()}catch(error){alert('导入失败：'+error.message)}}
