const POOLS={
  limited:{title:'限定卡池',draws:50,pity:50,rate:.01231,upRate:.5,guaranteedUp:true,perKey:3,keyName:'红钥匙',rule:'单张出金率 1.231% · 连续 50 张未出金时保底当期 UP · 自然出金时 UP 占 50% · 自然出金会重置保底'},
  mixed:{title:'双 UP 混池',draws:50,pity:50,rate:.01231,upRate:.5,guaranteedUp:true,perKey:3,keyName:'红钥匙',rule:'两张永恒品质卡共享 50% UP：默认新卡 25%、返场卡 25% · 保底 UP 默认在两张卡中各占 50% · 自然出金会重置保底'},
  permanent:{title:'常驻卡池',draws:20,pity:20,rate:.01914,upRate:0,guaranteedUp:false,perKey:5,keyName:'金钥匙',rule:'单张出金率 1.914% · 20 张必出一张金卡 · 常驻池没有 UP'},
}
let pool='limited';const $=id=>document.getElementById(id),pct=value=>(value*100).toFixed(value>.995?1:2)+'%',fmt=value=>Number(value).toFixed(2).replace(/\.00$/,'')
function render(){const cfg=POOLS[pool],draws=Math.max(1,Math.min(300,Number($('draws').value)||1)),pity=Math.min(cfg.pity-1,Number($('pity').value)||0),result=ProbabilityCore.calculate({draws,startPity:pity,baseGoldRate:cfg.rate,pityMax:cfg.pity,upRate:cfg.upRate,guaranteedUp:cfg.guaranteedUp})
  $('draws').value=draws
  const mixed=pool==='mixed',singleCard=mixed?ProbabilityCore.calculate({draws,startPity:pity,baseGoldRate:cfg.rate,pityMax:cfg.pity,upRate:.25,pityTargetRate:.5}):result
  $('poolTitle').textContent=cfg.title;$('pity').max=cfg.pity-1;$('pity').value=pity;$('pityHint').textContent=`已垫 ${pity} / ${cfg.pity} 张`;$('ruleText').textContent=cfg.rule
  const limited=pool!=='permanent';$('mainLabel').textContent=mixed?'预计获得两张 UP 合计':limited?'预计获得 UP':'预计获得金卡';$('expected').textContent=fmt(limited?result.expectedUp:result.expectedGold);$('rangeText').textContent=`约 80% 的结果落在 ${limited?result.upRange.join('～'):result.goldRange.join('～')} 张`;$('chanceLabel').textContent=limited?'至少 1 张任意 UP':'至少 1 张金卡';$('atLeastOne').textContent=pct(limited?result.atLeastOneUp:result.atLeastOneGold);$('expectedGold').textContent=fmt(result.expectedGold);$('atLeastGold').textContent=pct(result.atLeastOneGold);$('keyCost').textContent=`${Math.ceil(draws/cfg.perKey)} 把${cfg.keyName}`
  $('mixedSummary').hidden=!mixed;if(mixed){$('newExpected').textContent=fmt(singleCard.expectedUp)+' 张';$('returnExpected').textContent=fmt(singleCard.expectedUp)+' 张';$('newChance').textContent=`至少 1 张：${pct(singleCard.atLeastOneUp)}`;$('returnChance').textContent=`至少 1 张：${pct(singleCard.atLeastOneUp)}`}
  const dist=limited?(mixed?singleCard.upDist:result.upDist):result.goldDist,entries=Object.entries(dist).map(([count,prob])=>[Number(count),prob]).filter(([,prob])=>prob>=.001).sort((a,b)=>a[0]-b[0]),max=Math.max(...entries.map(x=>x[1]),1);$('distTitle').textContent=mixed?'新卡数量概率分布':limited?'UP 数量概率分布':'金卡数量概率分布';$('distribution').innerHTML=entries.map(([count,prob])=>`<div class="dist-row"><b>${count} 张</b><div class="bar"><i style="width:${prob/max*100}%"></i></div><strong>${pct(prob)}</strong></div>`).join('')
  $('explanation').innerHTML=mixed?`抽 <b>${draws} 张</b>时，两张 UP 合计平均约 <b>${fmt(result.expectedUp)} 张</b>；其中新卡平均约 <b>${fmt(singleCard.expectedUp)} 张</b>，至少获得一张新卡的概率为 <b>${pct(singleCard.atLeastOneUp)}</b>。返场卡在均分权重下数值相同，但两者是分别计算的。`:limited?`抽 <b>${draws} 张</b>时，平均约有 <b>${fmt(result.expectedUp)} 张 UP</b>。至少获得一张 UP 的概率为 <b>${pct(result.atLeastOneUp)}</b>。这里的“预计”是大量玩家重复同样抽数后的平均值，不是必得数量。`:`抽 <b>${draws} 张</b>时，至少出现一张金卡的概率为 <b>${pct(result.atLeastOneGold)}</b>，平均约 <b>${fmt(result.expectedGold)} 张金卡</b>。保底会让结果不同于简单的独立概率公式。`
}
let renderTimer;const scheduleRender=()=>{clearTimeout(renderTimer);renderTimer=setTimeout(render,80)};document.querySelector('.pool-tabs').onclick=e=>{const button=e.target.closest('[data-pool]');if(!button)return;pool=button.dataset.pool;document.querySelectorAll('[data-pool]').forEach(x=>x.classList.toggle('active',x===button));$('draws').value=POOLS[pool].draws;$('pity').value=0;render()};document.querySelector('.quick').onclick=e=>{const button=e.target.closest('[data-draws]');if(button){$('draws').value=button.dataset.draws;render()}};$('draws').oninput=scheduleRender;$('pity').oninput=scheduleRender;render()
