-- 在 Supabase SQL Editor 中执行，并在 Authentication > Sign In / Providers 启用 Allow anonymous sign-ins。
alter table public.herb_posts add column if not exists user_id uuid references auth.users(id);
alter table public.cook_posts add column if not exists user_id uuid references auth.users(id);
alter table public.trade_posts add column if not exists user_id uuid references auth.users(id);
alter table public.herb_posts add column if not exists completed_at bigint;
alter table public.cook_posts add column if not exists completed_at bigint;
alter table public.trade_posts add column if not exists completed_at bigint;

create table if not exists public.post_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null default auth.uid() references auth.users(id),
  post_type text not null check (post_type in ('herb','cook','trade')),
  post_id text not null,
  reason text not null check (char_length(reason) between 1 and 200),
  created_at timestamptz not null default now(),
  unique (reporter_id, post_type, post_id)
);

alter table public.herb_posts enable row level security;
alter table public.cook_posts enable row level security;
alter table public.trade_posts enable row level security;
alter table public.post_reports enable row level security;

do $$
declare t text;
begin
  foreach t in array array['herb_posts','cook_posts','trade_posts'] loop
    execute format('drop policy if exists "public read" on public.%I', t);
    execute format('drop policy if exists "signed insert" on public.%I', t);
    execute format('drop policy if exists "owner update" on public.%I', t);
    execute format('drop policy if exists "owner delete" on public.%I', t);
    execute format('create policy "public read" on public.%I for select using (completed_at is null)', t);
    execute format('create policy "signed insert" on public.%I for insert to authenticated with check (user_id = auth.uid())', t);
    execute format('create policy "owner update" on public.%I for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid())', t);
    execute format('create policy "owner delete" on public.%I for delete to authenticated using (user_id = auth.uid())', t);
  end loop;
end $$;

drop policy if exists "report insert" on public.post_reports;
create policy "report insert" on public.post_reports for insert to authenticated with check (reporter_id = auth.uid());

create index if not exists herb_posts_user_id_idx on public.herb_posts(user_id);
create index if not exists cook_posts_user_id_idx on public.cook_posts(user_id);
create index if not exists trade_posts_user_id_idx on public.trade_posts(user_id);
