const assert=require('assert'),fs=require('fs')
const html=fs.readFileSync('creation.html','utf8'),js=fs.readFileSync('creation.js','utf8'),sql=fs.readFileSync('creation-migration.sql','utf8')
const account=fs.readFileSync('account.js','utf8'),deck=fs.readFileSync('deck-community.js','utf8')
for(const key of ['album','outfit','art','meme','guide'])assert.ok(js.includes(`['${key}'`)||js.includes(`value="${key}"`))
for(const table of ['creation_works','creation_favorites','creation_reports','creation_admins','profiles','deck_submissions'])assert.ok(sql.includes(`public.${table}`))
assert.ok(sql.includes("status='approved'"));assert.ok(sql.includes("status='pending'"));assert.ok(sql.includes("bucket_id='creation-images'"))
assert.ok(js.includes('if(paths.length)await sb.storage.from(BUCKET).remove(paths)'),'upload rollback missing')
assert.ok(js.includes('requireEmail()'),'creation actions must require email login')
assert.ok(sql.includes('public.has_email_identity()'),'email identity must be enforced by RLS')
assert.ok(account.includes('signInWithOtp')&&account.includes('verifyOtp'),'email OTP flow missing')
assert.ok(deck.includes('cards.length!==8')&&deck.includes('partners.length!==3'),'deck cardinality validation missing')
assert.ok(deck.includes('selected_for_miniprogram'),'mini-program selection flow missing')
assert.ok(deck.includes('cards:r.cards.map(x=>[x])'),'mini-program export shape missing')
assert.ok(!html.includes('评论'));assert.ok(!html.includes('私信'));assert.ok(html.includes('投稿先审核'))
console.log('external creation plaza tests passed')
