const assert=require('assert'),core=require('../probability-core.js')
let result=core.calculate({draws:50,startPity:0,baseGoldRate:.01231,pityMax:50,upRate:.5,guaranteedUp:true})
assert.ok(result.upDist[0]>0)
assert.ok(result.expectedUp>0)
result=core.calculate({draws:1,startPity:19,baseGoldRate:.01914,pityMax:20,upRate:0})
assert.equal(result.atLeastOneGold,1)
result=core.calculate({draws:1,startPity:49,baseGoldRate:.01231,pityMax:50,upRate:.25,pityTargetRate:.5})
assert.equal(result.atLeastOneUp,.5)
result=core.calculate({draws:0,startPity:0,baseGoldRate:.1,pityMax:20,upRate:.5})
assert.equal(result.expectedGold,0)
console.log('probability-core tests passed')
